### ISSUE TITLE
Spelling mistake on readme

### ISSUE THREAD

**Issue by molinto** [crypto-browserify/sha.js#21]
var sha512 = createHash'sha512')
Should be:
var sha512 = createHash('sha512')

**Comment by dcousens** [comment]
@molinto good find, why not make a PR?

**Comment by molinto** [comment]
Sorry, I'm just lazy

**Comment by dcousens** [comment]
It's totally faster just to make the edit using the inline editor then to
specify it in an issue?

In any case,  all good haha.

**Comment by molinto** [comment]
^ Sorry, didn't know you could do that.  My bad.

**Comment by molinto** [comment]
Updated
