### ISSUE TITLE
Extract hash.js for use in ripemd160

### ISSUE THREAD

**Issue by dcousens** [crypto-browserify/sha.js#25]
Right now `hash.js` is a really good plug-and-play model for block hashs. 
Perhaps we could extract it to a module where it can be used to easily implement block hashes that support streaming.

This would at least stop me having to duplicate it for ripemd160.

**Comment by dcousens** [comment]
@dominictarr thoughts?

**Comment by dominictarr** [comment]
sure! good idea, make a new module and then add a pr so that this module depends on it

**Comment by dcousens** [comment]
@calvinmetcalf relevant to https://github.com/crypto-browserify/cipher-base?

**Comment by calvinmetcalf** [comment]
yes probably a good idea

**Comment by fanatid** [comment]
Any ideas about name for this new module?

**Comment by calvinmetcalf** [comment]
browserify-md5?

**Comment by fanatid** [comment]
@calvinmetcalf no, this is other issue :smile: 
support node streams in sha.js and ripemd160 (and in md5 that we want to extract) without cipher-base

**Comment by calvinmetcalf** [comment]
ah then like hash-base or something

**Comment by fanatid** [comment]
nice name, I'll try do this in nearest time!

**Comment by dcousens** [comment]
@fanatid maybe find out what the padding standard is called, and use that with the name.

**Comment by dcousens** [comment]
Thanks @fanatid

**Comment by dcousens** [comment]
Now just for ripemd160 :+1:
