### ISSUE TITLE
Cannot find module 'graceful-fs' from '.../node_modules/sha'

### ISSUE THREAD

**Issue by maiermic** [crypto-browserify/sha.js#27]
If I require sha.js (1.3.0) in a browserify application, I get an error message:
```Cannot find module 'graceful-fs' from '.../node_modules/sha'```

**Comment by dcousens** [comment]
@maiermic `sha` is a package by @ForbesLindesay (see https://www.npmjs.com/package/sha).
If you want to use `sha.js`,  you need to do `npm install sha.js`.

**Comment by maiermic** [comment]
Thanks. I found your github project, searched on npm for it and found [sha](https://www.npmjs.com/package/sha) (overseeing the missing _.js_). It would be useful to link to your npm release on github.

**Comment by dcousens** [comment]
#28, feel free to PR.

**Comment by maiermic** [comment]
I tried to push my changes on a new branch to create an PR, but I get an error:
```
remote: Permission to crypto-browserify/sha.js.git denied to maiermic.
fatal: unable to access 'https://github.com/crypto-browserify/sha.js.git/': The requested URL returned error: 403
```

**Comment by ForbesLindesay** [comment]
You need to "fork" the project first (the button at the top right of the page on GitHub).  This creates a separate copy of the repository that you have full access to.  Then once you've pushed your changes to that copy you can create the pull request to ask your changes to be merged into this repo.
