### ISSUE TITLE
Bug in sha implementation (likely due to international characters)

### ISSUE THREAD

**Issue by boucher** [crypto-browserify/sha.js#37]
You can see the bug in this example:
https://tonicdev.com/boucher/573e107d8596081100e6a4d9

The hash returned from sha.js should be the same as the one from the built in crypto package, but isn't.

**Comment by fanatid** [comment]
```
$ node -v
v6.1.0
$ npm ls --depth=0 | grep sha.js
`-- sha.js@2.4.5
$ node
var s = 'Русский язык1'
var SHA1 = require('sha.js').sha1
new SHA1().update(s).digest('hex')
// => 43078a51a0771278729e446a587b0442fecebfcd
require('crypto').createHash('sha1').update(s).digest('hex')
// => 43078a51a0771278729e446a587b0442fecebfcd
```
ЧЯДНТ?

**Comment by fanatid** [comment]
@boucher should I run test in browser instead node?

**Comment by boucher** [comment]
Run it in any version of node prior to 6

**Comment by fanatid** [comment]
https://github.com/nodejs/node/pull/5522
It's not a bug, crypto-browserify just not supported node 6 yet..
```
$ node -v
v6.1.0
$ npm ls --depth=0 | grep sha.js
`-- sha.js@2.4.5
$ node
var s = 'Русский язык1'
require('crypto').createHash('sha1').update(s).digest('hex')
// => 43078a51a0771278729e446a587b0442fecebfcd
require('crypto').createHash('sha1').update(new Buffer(s, 'binary')).digest('hex')
// => 26c13d4b707714600f2aa1a60b4147bb3ba28868
```

**Comment by fanatid** [comment]
not sure, but https://github.com/crypto-browserify/sha.js/pull/36 should fix this

**Comment by boucher** [comment]
The issue is not that things do not work in Node 6, they don't work in Node 5 or earlier (and they don't work in the browser, which is where support is critical).

**Comment by boucher** [comment]
If you download the zip file in the linked issue above (node-browserify#1553) you can get a complete example you can run yourself.

**Comment by fanatid** [comment]
Argh, totally missed up with this..
You were right, it wasn't consistent with node < 6, but we can't support all node versions at one moment!
Since node 6 convert input to Buffer with utf8, I don't think that we should fix something here.

**Comment by boucher** [comment]
:( This means that browserify is broken in anything less than Node 6,
including Node 4 which is theoretically the most stable current release.

**Comment by dcousens** [comment]
> You were right, it wasn't consistent with node < 6, but we can't support all node versions at one moment!

Can you elaborate on your findings?
