### ISSUE TITLE
Switch to BSD-3

### ISSUE THREAD

**Issue by bastien-roucaries** [crypto-browserify/sha.js#42]
Hi,

Your package is derivated from a BSD-3-clause license (see *) under term different of expat license.

Thus you violate original author license. 

expat license will be transformed to BSD-3 clause... 

Could you change the license in order to be packaged for debian

Thanks you

*Copyright (c) 1998 - 2009, Paul Johnston & Contributors
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

Neither the name of the author nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by dcousens** [comment]
To be honest,  we could probably completely ditch that as this code has been entirely re-written...

**Comment by dominictarr** [comment]
yes, this has been completely rewritten, but I do think it should include an acknowledgement that it started out as that. It's theisis's ship, if you fork an open source project, and rewrite every line of code, is it still the same project?

**Comment by dominictarr** [comment]
The only bits that still resemble the original are variable naming in bits like
https://github.com/crypto-browserify/sha.js/blob/master/sha1.js#L50-L54

**Comment by dcousens** [comment]
We could leave an acknowledgement, but leave the license as is? IANAL, just thinking

**Comment by bastien-roucaries** [comment]
Le 28 mars 2017 05:54:47 GMT+02:00, Daniel Cousens <notifications@github.com> a écrit :
>We could leave an acknowledgement, but leave the license as is? IANAL,
>just thinking
I will not play with this kind of game...

 Bsd-3 does not taint tour software. It will be limited to this module.

And you could ask original author to relicence the remaining bit to expat...

Safe and allow inclusion on debian/ubuntu

Bastien 


-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by dcousens** [comment]
@dominictarr leaving this one to you...

**Comment by dominictarr** [comment]
@bastien-roucaries we are not trynig to be difficult just to understand what we need to do.

**Comment by dominictarr** [comment]
@bastien-roucaries are you saying we have to change the license back to the original one?
can it say "Copyright (c) 1998 - 2009, Paul Johnston & Contributors, Copyright (c) 2013-2014 sha.js contributors"?

**Comment by dominictarr** [comment]
or can we put the original license in a comment at the top of the files that currently mention that author?

**Comment by bastien-roucaries** [comment]
Le 28 mars 2017 08:27:54 GMT+02:00, Dominic Tarr <notifications@github.com> a écrit :
>@bastien-roucaries are you saying we have to change the license back to
>the original one?
>can it say "Copyright (c) 1998 - 2009, Paul Johnston & Contributors,
>Copyright (c) 2013-2014 sha.js contributors"?

BSD 3 is a superset of expat.

I believe it is the safer and quicker zone

Bastien

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by dominictarr** [comment]
@bastien-roucaries I don't understand what this "expat" thing is, they used BSD. If you want us to fix the license can you please answer my questions above

**Comment by bastien-roucaries** [comment]
Le 28 mars 2017 08:41:06 GMT+02:00, Dominic Tarr <notifications@github.com> a écrit :
>@bastien-roucaries I don't understand what this "expat" thing is, they
>used BSD. If you want us to fix the license can you please answer my
>questions above 


Expat is that you call mit

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by dcousens** [comment]
> MIT License (Expat)

https://www.debian.org/legal/licenses/mit

**Comment by dcousens** [comment]
Do we just change our license to BSD3?

**Comment by dcousens** [comment]
@bastien-roucaries could you please submit a PR for what exactly needs to change?

**Comment by dcousens** [comment]
ping @bastien-roucaries

**Comment by bastien-roucaries** [comment]
Will do this week...

Ping me if i forget

Le 22 janv. 2018 01:13, "Daniel Cousens" <notifications@github.com> a
écrit :

ping @bastien-roucaries <https://github.com/bastien-roucaries>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/crypto-browserify/sha.js/issues/42#issuecomment-359294895>,
or mute the thread

**Comment by bastien-roucaries** [comment]
Changing license will do: the licence is
Copyright (c) 1998 - 2009, Paul Johnston & Contributors
Copyright (c) 2013-2017 your name

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer. Redistributions in binary
form must reproduce the above copyright notice, this list of conditions and
the following disclaimer in the documentation and/or other materials
provided with the distribution.

Neither the name of the author nor the names of its contributors may be
used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.

**Comment by dcousens** [comment]
@bastien-roucaries PR? :+1:
