### ISSUE TITLE
Use Safe Buffer

### ISSUE THREAD

**Issue by tad88dev** [crypto-browserify/sha.js#49]
NodeJs is suggest developer to switch to `.from()`/`.alloc()`/`.allocUnsafe()` instead of `new Buffer()`.
There are many lines of code still use Buffer constructor
https://github.com/crypto-browserify/sha.js/blob/master/sha512.js#L241

**Comment by dcousens** [comment]
https://www.npmjs.com/package/safe-buffer

**Comment by dcousens** [comment]
@tad88dev PR welcome :+1:

**Comment by dcousens** [comment]
resolved with #50
