### ISSUE TITLE
Test folder should be added to .npmignore

### ISSUE THREAD

**Issue by vorg** [crypto-browserify/sha.js#5]
Test are needed only for development and shouldn't be distributed on npm where they add 700KB to every library that uses sha.js.

**Comment by dcousens** [comment]
@dominictarr out of interest, does leaving the tests in serve any purpose?

**Comment by dominictarr** [comment]
I leave my tests in my modules, because I believe that one day, a great hero will arise and do something awesome testing all the modules on npm. If the tests are excluded this can't happen.

**Comment by dcousens** [comment]
@dominictarr haha

Could they not just download all the git repos instead if they wanted to test against the source?
I guess it depends what you think of when you think of npm as a publication platform.  

Whether it is literally publication of the source code of the entire package, or if it is just the publication of the code as it will be used.

**Comment by dominictarr** [comment]
@dcousens the trouble is that the binding between the published package and the git repo is not very strong. it's just a url, what is the actual code? there is a sha1 hash of the tarball, so you could check out the repo with git and then repackage it to check you have exactly the right code. Unfortunately tar archives are not as deterministic as they could be, containing mtime and ctime, so it's not guaranteed that archiving the exact same files produces the exact same tarball.

Remember tar and unix was invented _before cryptographic hashes!!!_

It would just be way easier to build the everything tester and secure it if the tests are published.

**Comment by dominictarr** [comment]
or, invent a better file bundler that in cryptofriendly

**Comment by dcousens** [comment]
@dominictarr it scares me a little how easy it would be to screw over soooo many deployments #nsa.
Has any worked progressed on this?

Current decision is not in line with the merge here https://github.com/crypto-browserify/browserify-aes/issues/24.

**Comment by exogen** [comment]
I hope this can be revisited, the `sha.js/test` dir in my `node_modules` is by far one of the largest at 1.4MB. It is standard practice to exclude tests from the npm package. While some hypothetical person somewhere might want to peek at them (why wouldn't they just go to the repo?), more likely 99% of `sha.js` installs are by people who don't even know it's there and don't care about it, it's merely somewhere deep in their dependency tree. It's much better to be respectful of your users' install time and disk space. :)

**Comment by dcousens** [comment]
I'm personally inclined to agree with @exogen.  I'd sooner prefer to just go to the repository than iterate my node modules.

**Comment by dcousens** [comment]
@fanatid sneakily did this in the recent `hash-base` PR (my bad for not noticing until going back through these issues)... @dominictarr do I need to release a patch to put them back?

**Comment by dominictarr** [comment]
our call

**Comment by dominictarr** [comment]
I mean, Your call
